import type { Metadata } from 'next';
import Link from 'next/link';
import Header from '../../components/layout/Header';

export const metadata: Metadata = {
  title: 'About Saveyojob.com — Free AI Career Risk Tool',
  description:
    'Saveyojob.com is a free tool that tells you exactly which tasks in your job are being automated — and gives you a personalized reskilling roadmap.',
};

export default function AboutPage() {
  return (
    <>
      <Header />
      <main className="max-w-[720px] mx-auto px-5 sm:px-8 py-16">

        <div className="mb-12">
          <span className="text-[11px] font-bold uppercase tracking-[0.16em] text-fire block mb-3">
            About
          </span>
          <h1 className="text-[36px] sm:text-[42px] font-bold tracking-[-0.03em] text-ink leading-tight mb-5">
            We help workers stay ahead of AI.
          </h1>
          <p className="text-[17px] text-ink-2 leading-relaxed">
            Saveyojob.com is a free AI career risk tool that tells you exactly which tasks in your job
            are being automated — and gives you a personalized, actionable reskilling roadmap.
          </p>
        </div>

        <div className="space-y-10 mb-16">
          <section>
            <h2 className="text-[20px] font-bold text-ink mb-3">The problem we&apos;re solving</h2>
            <p className="text-[15px] text-ink-2 leading-relaxed mb-3">
              51% of American workers actively worry AI will replace their job. 92 million jobs are projected
              to be displaced globally by 2030 (WEF). Yet most people have no idea which parts of their
              specific job are at risk — let alone what to do about it.
            </p>
            <p className="text-[15px] text-ink-2 leading-relaxed">
              Every existing tool gives a generic risk score with no guidance. Nobody had built a
              task-level, personalized roadmap generator with integrated course recommendations.
              Until now.
            </p>
          </section>

          <section>
            <h2 className="text-[20px] font-bold text-ink mb-3">What we do</h2>
            <div className="space-y-4">
              {[
                {
                  n: '01',
                  title: 'Task-level analysis',
                  desc: 'We break down every task in your specific job and show you exactly which are being automated — and by which AI tools.',
                },
                {
                  n: '02',
                  title: 'Personalized roadmap',
                  desc: 'Based on your experience level and goals, we build a week-by-week learning roadmap matched to your schedule.',
                },
                {
                  n: '03',
                  title: 'Real course recommendations',
                  desc: 'Curated courses from Coursera, LinkedIn Learning, DeepLearning.AI, and more — each chosen for your specific situation.',
                },
              ].map(item => (
                <div key={item.n} className="flex gap-5 p-5 bg-surface border border-line rounded-xl">
                  <div className="text-[22px] font-extrabold text-fire leading-none shrink-0">{item.n}</div>
                  <div>
                    <div className="text-[15px] font-bold text-ink mb-1">{item.title}</div>
                    <p className="text-[13px] text-ink-2 leading-relaxed">{item.desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </section>

          <section>
            <h2 className="text-[20px] font-bold text-ink mb-3">Our data sources</h2>
            <p className="text-[15px] text-ink-2 leading-relaxed mb-3">
              Risk scores are based on automation probability research from Oxford University (Frey &amp; Osborne),
              McKinsey Global Institute, and the World Economic Forum. Salary data comes from the US Bureau of
              Labor Statistics. AI tool assessments are updated regularly as the technology evolves.
            </p>
            <p className="text-[15px] text-ink-2 leading-relaxed">
              The personalized roadmap is generated by Claude (Anthropic), one of the most capable AI
              systems available, using a specialized prompt trained on career transition research.
            </p>
          </section>

          <section>
            <h2 className="text-[20px] font-bold text-ink mb-3">Business model</h2>
            <p className="text-[15px] text-ink-2 leading-relaxed">
              Saveyojob.com is free to use, always. We earn a commission when users enroll in
              recommended courses through our affiliate partnerships with Coursera, LinkedIn Learning,
              and other platforms. This never influences which courses we recommend — only the highest-rated,
              most relevant courses make the cut.
            </p>
          </section>
        </div>

        <div className="border-t border-line pt-10 text-center">
          <Link
            href="/"
            className="inline-block px-8 py-4 bg-fire text-bg font-bold text-[15px] rounded-xl hover:brightness-105 transition-all duration-150"
          >
            Check your AI risk score — free →
          </Link>
        </div>

      </main>

      <footer className="border-t border-line bg-surface py-8 px-5 sm:px-8">
        <div className="max-w-[720px] mx-auto flex flex-col sm:flex-row items-center justify-between gap-3 text-[12px] text-ink-3">
          <span>© {new Date().getFullYear()} Saveyojob.com</span>
          <div className="flex gap-5">
            <Link href="/privacy" className="hover:text-ink transition-colors">Privacy</Link>
            <Link href="/about" className="hover:text-ink transition-colors">About</Link>
            <Link href="/jobs" className="hover:text-ink transition-colors">All Jobs</Link>
          </div>
        </div>
      </footer>
    </>
  );
}
